### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Code1705**
made some changes in the css file, could you merge my PR please?

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly share your work  so that I can review your changes

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
any update?

**Comment by Code1705** [comment]
Screenshot (55)

**Comment by Code1705** [comment]
above given is the screenshot of the changed page , now could you please merge my pr?

**Comment by codervivek5** [comment]
also change the color of the formfill heading and their respected desc.

**Comment by Code1705** [comment]
Screenshot (59)

**Comment by Code1705** [comment]
its done as per u said

**Comment by Code1705** [comment]
you haven't merged my pr ,please could you do so?

**Comment by codervivek5** [comment]
First Solve the merge conflict then I will merge your PR

**Pull request closed without merging**
