### PR TITLE
Add about us page (Issue #45)

### PR DESCRIPTION
**Pull request by imkrishnasarathi**

### CODE REVIEW

**Comment by codervivek5** [comment]
Kindly solve merge conflict

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Comment by codervivek5** [comment]
Can I see your changes?

**Comment by KrishnaTheCoder756** [comment]
I have added the about_us.html and about_us.css. You can view the code in those files

**Review by codervivek5 — APPROVED** [review]

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thank you for your contribution :)

**Comment by KrishnaTheCoder756** [comment]
maybe due to some connection issues with the main file, the about us page is still not showing up. However, the forked project is working well

**Comment by KrishnaTheCoder756** [comment]
they are searching for index.html i see

**Comment by imkrishnasarathi** [comment]
Thanks for merging the PR. If you wish, you can show some support to this 13 yo kid by buying me just one coffee - [Buy me a coffee](https://www.buymeacoffee.com/imkrishnasarathi)
You can also follow me on twitter - [twitter](https://twitter.com/CodesKae) and [Instagram](https://instagram.com/imkrishnasarathi) . I'll follow back

**Pull request merged**
