### PR TITLE
Improved Testimonial Page

### PR DESCRIPTION
**Pull request by TuhinBanerjee31**
Changed the Testimonial UI.
Improved responsiveness for all three screen types (desktop, tab, mobile)
Fix the slider functionality for the testimonial swipe
Fixed the navbar for the page
Screenshot (60)
Screenshot (61)
Screenshot (62)

### CODE REVIEW

**Comment by codervivek5** [comment]
make it 1x3 for desktop mode

**Comment by codervivek5** [comment]
Kindly solve mere conflict

**Comment by TuhinBanerjee31** [comment]
fixing it quickly

**Review by codervivek5 — APPROVED** [review]

**Comment by TuhinBanerjee31** [comment]
Pls put  difficulty and jwoc tag on my PR @codervivek5

**Pull request merged**
