### PR TITLE
Mobile app UI has been added !!

### PR DESCRIPTION
**Pull request by ghost**
Hello!
i have created a mobile app UI (issue #8 )  and added it into mobile-app-ui folder in the form of picture, pdf and .fig file.
please review it and proceed with the PR.

Checklist
[ ✓] I am making a proper pull request, not spam.
[ ✓] I've checked the issue list before deciding what to submit.

Thank you!
image

### CODE REVIEW

**Comment by codervivek5** [comment]
perfect work 👏👏👏

**Comment by codervivek5** [comment]
Kindly send Figma file for next process

**Comment by itsshahinhere** [comment]
> perfect work clapclapclap

kindly add the jwoc tag to this PR :)

**Comment by itsshahinhere** [comment]
kindly add "JWOC" label in this PR please!

**Pull request merged**
