### PR TITLE
mapped url backend

### PR DESCRIPTION
**Pull request by Saedbhati**

### CODE REVIEW

**Comment by Saedbhati** [comment]
https://saedbhati-automatic-xylophone-4px45wqv7wg27g6-8000.preview.app.github.dev/

**Comment by Saedbhati** [comment]
here is the link

**Comment by codervivek5** [comment]
image
link is not find

**Review by Saedbhati — COMMENTED** [review]
mapped url

**Comment by Saedbhati** [comment]
what is merge conflict

**Comment by codervivek5** [comment]
Try to chech pin comment in discord then you can learn how to solve it

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Pull request closed without merging**
